#include "mibprofile.h"
#include "mibeffectiveplan.h"
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>
#include <algorithm>
#include <iostream>

namespace {
bool check(bool v,const char*m){if(!v)std::cerr<<"FAIL: "<<m<<'\n';return v;}
bool writeFile(const QString&p,const QByteArray&c){QDir().mkpath(QFileInfo(p).absolutePath());QFile f(p);return f.open(QIODevice::WriteOnly)&&f.write(c)==c.size();}
QByteArray mib(const QByteArray&i){return i+" DEFINITIONS ::= BEGIN\nEND\n";}
}

int main(int argc,char**argv){QCoreApplication app(argc,argv);bool ok=true;QTemporaryDir temp;
 const QString repo=temp.filePath("profiles.json");MibProfileService service{MibProfileRepository(repo)};
 ok&=check(service.profiles().size()==2&&service.find(MibProfileDefinitions::allId())->type==MibProfileType::Custom,"built-ins migrate once to ordinary Profiles");
 ok&=check(service.rename(MibProfileDefinitions::allId(),"Everything I selected")&&service.remove(MibProfileDefinitions::allId()),"former All MIBs is editable and deletable");
 MibProfileService afterDelete{MibProfileRepository(repo)};ok&=check(!afterDelete.find(MibProfileDefinitions::allId()),"All MIBs is not regenerated");
 const QString emptyId=afterDelete.create("Empty manifest Profile");ok&=check(afterDelete.find(emptyId)&&MibProfileIsManifest(*afterDelete.find(emptyId))&&afterDelete.find(emptyId)->roots.isEmpty(),"new Profiles begin as empty manifests");
 const QString root=temp.filePath("Catalog"),a=QDir(root).filePath("BatchA/rfc4188.mib"),b=QDir(root).filePath("BatchB/BRIDGE-MIB.mib"),multi=QDir(root).filePath("BatchA/vendor-file.mib");
 writeFile(a,mib("BRIDGE-MIB")+"-- A\n");writeFile(b,mib("BRIDGE-MIB")+"-- B\n");writeFile(multi,mib("VENDOR-ROOT-MIB")+mib("VENDOR-TC-MIB"));
 QString error;const QString id=afterDelete.create("Fabric Engine 9.1",&error);ok&=check(afterDelete.addFiles(id,{a,multi},MibProfileMemberReason::Added,&error),"Add Files snapshots exact files");
 const MibProfileRecord exact=*afterDelete.find(id);ok&=check(exact.roots.size()==2&&exact.roots.first().sha256.size()==64&&exact.explicitModules.contains("BRIDGE-MIB")&&exact.explicitModules.contains("VENDOR-TC-MIB")&&!exact.orderedScopes.isEmpty(),"root path hash identities and scope persist");
 MibDependencyIndex catalog(temp.filePath("index.json"));catalog.update({root});
 const auto global=catalog.providersFor("BRIDGE-MIB"),scoped=catalog.providersFor("BRIDGE-MIB",QFileInfo(a).absolutePath(),MibCatalogProviderScope::ExactFolder);
 ok&=check(global.size()==2&&scoped.size()==1&&scoped.first().canonicalPath==QFileInfo(a).canonicalFilePath(),"Catalog duplicates remain distinct and folder lookup stays scoped");
 const auto resolve=[&catalog](const MibProfileRecord&p){MibEffectivePlanResolverInput i;i.id=p.id;i.roots=p.roots;i.orderedScopes=MibProfileScopePaths(p);i.pins=p.providerPins;return MibEffectiveRuntimePlanResolver().resolve(i,catalog);};
 const auto planA=resolve(exact);ok&=check(planA.member("BRIDGE-MIB")&&planA.member("BRIDGE-MIB")->provider.canonicalPath==QFileInfo(a).canonicalFilePath(),"Profile selects exact provider A");
 MibProfileRecord exactB=exact;exactB.roots=MibProfileMembersFromFiles({b});exactB.explicitModules=MibProfileMemberIdentities(exactB.roots);const auto planB=resolve(exactB);
 ok&=check(planB.member("BRIDGE-MIB")&&planB.member("BRIDGE-MIB")->provider.canonicalPath==QFileInfo(b).canonicalFilePath()&&planA.sha256!=planB.sha256,"provider B cannot silently replace A");
 MibProfileService reload{MibProfileRepository(repo)};const MibProfileRecord saved=*reload.find(id);ok&=check(saved.roots==exact.roots&&saved.orderedScopes==exact.orderedScopes,"schema-5 roots and ordered scope round trip");
 const QString substitute=QDir(root).filePath("BatchA/provider-with-old-content.mib");writeFile(substitute,mib("BRIDGE-MIB")+"-- A\n");writeFile(a,mib("BRIDGE-MIB")+"-- changed\n");ok&=check(MibProfileMemberCurrentState(saved.roots.first())==MibProfileMemberState::Changed,"content change detected");catalog.update({root});const auto changedPlan=resolve(saved);ok&=check(!changedPlan.authorityError.isEmpty(),"changed root is a hard error and cannot substitute same identity elsewhere");QFile::remove(multi);
 auto mm=std::find_if(saved.roots.cbegin(),saved.roots.cend(),[](const auto&m){return m.identities.contains("VENDOR-ROOT-MIB");});ok&=check(mm!=saved.roots.cend()&&MibProfileMemberCurrentState(*mm)==MibProfileMemberState::Missing,"missing root preserves intent");
 const QString folder=QDir(root).filePath("Folder"),one=QDir(folder).filePath("one.mib"),two=QDir(folder).filePath("nested/two.mib");writeFile(one,mib("ONE-MIB"));writeFile(two,mib("TWO-MIB"));
 const QString iid=reload.create("Individual",&error),fid=reload.create("Folder",&error);reload.addFiles(iid,{one,two},MibProfileMemberReason::Added,&error);reload.addFolder(fid,folder,&error);
 ok&=check(reload.find(iid)->roots==reload.find(fid)->roots,"recursive Add Folder equals individual root files");const auto snapshot=reload.find(fid)->roots;writeFile(QDir(folder).filePath("later.mib"),mib("LATER-MIB"));ok&=check(reload.find(fid)->roots==snapshot,"later addition does not regenerate roots");QFile::remove(one);const auto removed=std::find_if(reload.find(fid)->roots.cbegin(),reload.find(fid)->roots.cend(),[&one](const auto&m){return m.canonicalPath==QFileInfo(one).absoluteFilePath();});ok&=check(reload.find(fid)->roots==snapshot&&removed!=reload.find(fid)->roots.cend()&&MibProfileMemberCurrentState(*removed)==MibProfileMemberState::Missing,"later removal remains missing root intent");
 const QString legacyPath=temp.filePath("legacy.json");writeFile(legacyPath,QJsonDocument(QJsonObject{{"schemaVersion",3},{"profiles",QJsonArray{QJsonObject{{"id","legacy-folder"},{"name","Legacy Product"},{"type","folder"},{"directory",folder}}}}}).toJson());
 MibProfileService legacy{MibProfileRepository(legacyPath)};ok&=check(legacy.migrateLegacyFolderProfiles(&error)&&legacy.find("legacy-folder")&&MibProfileIsManifest(*legacy.find("legacy-folder")),"legacy folder Profile migrates to manifest snapshot with stable ID");const auto migrated=legacy.find("legacy-folder")->roots;writeFile(QDir(folder).filePath("post.mib"),mib("POST-MIB"));legacy.migrateLegacyFolderProfiles(&error);ok&=check(legacy.find("legacy-folder")->roots==migrated,"migrated folder snapshot never regenerates");
 const QString legacyRoot=temp.filePath("LegacyCatalog"),unique=QDir(legacyRoot).filePath("unique.mib"),dupA=QDir(legacyRoot).filePath("same/provider-A.mib"),dupB=QDir(legacyRoot).filePath("same/provider-B.mib");writeFile(unique,mib("UNIQUE-MIB"));writeFile(dupA,mib("DUP-MIB")+"-- A\n");writeFile(dupB,mib("DUP-MIB")+"-- B\n");MibDependencyIndex legacyIndex(temp.filePath("legacy-index.json"));legacyIndex.update({legacyRoot});
 const QString identityRepo=temp.filePath("identity-profiles.json");writeFile(identityRepo,QJsonDocument(QJsonObject{{"schemaVersion",3},{"profiles",QJsonArray{QJsonObject{{"id","identity-only"},{"name","Identity Only"},{"type","custom"},{"modules",QJsonArray{"UNIQUE-MIB","DUP-MIB","ABSENT-MIB"}}}}}}).toJson());MibProfileService identityProfiles{MibProfileRepository(identityRepo)};ok&=check(MibProfileRequiresExactMigration(*identityProfiles.find("identity-only")),"identity-only persistence is migration data, not runtime authority");ok&=check(identityProfiles.migrateLegacyProfiles(legacyIndex,&error),"legacy identity Profile conversion persists atomically");const auto *converted=identityProfiles.find("identity-only");ok&=check(converted&&MibProfileIsManifest(*converted)&&converted->roots.size()==1&&converted->roots.first().identities.contains("UNIQUE-MIB")&&converted->unresolvedLegacyModules==QStringList({"ABSENT-MIB","DUP-MIB"}),"legacy migration selects only unique roots and preserves unresolved intent");
 QFile::remove(dupB);legacyIndex.update({legacyRoot});ok&=check(identityProfiles.migrateLegacyProfiles(legacyIndex,&error)&&identityProfiles.find("identity-only")->roots.size()==2&&identityProfiles.find("identity-only")->unresolvedLegacyModules==QStringList{"ABSENT-MIB"},"unresolved legacy intent retries after Catalog refresh");MibProfileService identityReload{MibProfileRepository(identityRepo)};ok&=check(identityReload.find("identity-only")->roots.size()==2&&identityReload.find("identity-only")->unresolvedLegacyModules==QStringList{"ABSENT-MIB"},"manifest roots and unresolved intent survive restart");const QString forbiddenId=identityReload.create("No legacy authority",&error);MibProfileRecord forbidden=*identityReload.find(forbiddenId);forbidden.manifestVersion=0;forbidden.explicitModules={"IDENTITY-ONLY-MIB"};ok&=check(!identityReload.update(forbidden,&error),"normal editing cannot create legacy identity authority");
 const QString broadRoot=temp.filePath("BroadLibrary"),productFile=QDir(broadRoot).filePath("Vendor/Product/root.mib");writeFile(productFile,mib("PRODUCT-ROOT"));QStringList broadFiles{productFile};for(int i=0;i<20;++i){const QString path=QDir(broadRoot).filePath(QString("Standards/UNUSED-%1-MIB").arg(i));writeFile(path,mib(QString("UNUSED-%1-MIB").arg(i).toLatin1()));broadFiles.append(path);}MibProfileRecord broad;broad.id="broad";broad.name="Broad generated";broad.type=MibProfileType::Custom;broad.members=MibProfileMembersFromFiles(broadFiles);broad.unresolvedLegacyModules={"OLD-OVERINCLUSIVE-MIB"};const QString broadRepo=temp.filePath("broad.json");MibProfileRepository(broadRepo).save({broad},&error);MibDependencyIndex broadIndex(temp.filePath("broad-index.json"),broadRoot);broadIndex.update({broadRoot});MibProfileService broadService{MibProfileRepository(broadRepo)};ok&=check(broadService.migrateLegacyProfiles(broadIndex,&error)&&broadService.find("broad")->roots.size()==1&&broadService.find("broad")->roots.first().identities.contains("PRODUCT-ROOT")&&broadService.find("broad")->unresolvedLegacyModules.isEmpty(),"broad generated Standards membership becomes scope rather than roots");
 const QString exactRoot=temp.filePath("ExactLegacy"),top=QDir(exactRoot).filePath("top.mib"),dep=QDir(exactRoot).filePath("dep.mib"),orphan=QDir(exactRoot).filePath("orphan.mib");writeFile(top,"TOP-MIB DEFINITIONS ::= BEGIN\nIMPORTS x FROM DEP-MIB;\nEND\n");writeFile(dep,mib("DEP-MIB"));writeFile(orphan,mib("ORPHAN-MIB"));MibProfileRecord oldExact;oldExact.id="old-exact";oldExact.name="Old exact";oldExact.type=MibProfileType::Custom;oldExact.members=MibProfileMembersFromFiles({top,dep,orphan});const QString exactRepo=temp.filePath("old-exact.json");MibProfileRepository(exactRepo).save({oldExact},&error);MibDependencyIndex exactIndex(temp.filePath("old-exact-index.json"),exactRoot);exactIndex.update({exactRoot});MibProfileService exactService{MibProfileRepository(exactRepo)};ok&=check(exactService.migrateLegacyProfiles(exactIndex,&error)&&exactService.find("old-exact")->roots.size()==2&&MibProfileMemberIdentities(exactService.find("old-exact")->roots).contains("ORPHAN-MIB")&&!MibProfileMemberIdentities(exactService.find("old-exact")->roots).contains("DEP-MIB"),"old exact dependency becomes derived while unexplained member remains a root");
 const QString pinRoot=QDir(root).filePath("BatchA/pin-root.mib");writeFile(pinRoot,"PIN-ROOT DEFINITIONS ::= BEGIN\nIMPORTS x FROM BRIDGE-MIB;\nEND\n");catalog.update({root});const QString pinId=reload.create("Pinned",&error);reload.addFiles(pinId,{pinRoot},MibProfileMemberReason::Added,&error);MibProfileRecord pinned=*reload.find(pinId);pinned.providerPins.insert("BRIDGE-MIB",{QFileInfo(b).canonicalFilePath(),QString(64,'0'),"test choice"});ok&=check(reload.update(pinned,&error),"pin persists");MibProfileService pinReload{MibProfileRepository(repo)};ok&=check(pinReload.find(pinId)->providerPins.value("BRIDGE-MIB").reason=="test choice"&&resolve(*pinReload.find(pinId)).pinFailureModules.contains("BRIDGE-MIB"),"stale pin survives reload and fails hard");
 QFile json(repo);ok&=check(json.open(QIODevice::ReadOnly)&&json.readAll().contains("\"schemaVersion\": 5")&&MibProfileRepository(repo).ordinaryProfileMigrationComplete(),"schema-5 marker prevents regeneration");return ok?0:1;}
